# Generated by Django 3.2.6 on 2021-08-17 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quesmodel',
            name='op4',
        ),
        migrations.AddField(
            model_name='quesmodel',
            name='category',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='quesmodel',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
